audio_files:
  - name: "battery_check_failed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery_check_failed.wav"
  - name: "boot_up"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/boot_up.wav"
  - name: "controller_connected"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/controller_connected.wav"
  - name: "controller_disconnected"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/controller_disconnected.wav"
  - name: "down_finished"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/down_finished.wav"
  - name: "downing"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/downing.wav"
  - name: "enter_low_power_mode"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/enter_low_power_mode.wav"
  - name: "exit_low_power_mode"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/exit_low_power_mode.wav"
  - name: "imu_connected"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/imu_connected.wav"
  - name: "imu_disconnected"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/imu_disconnected.wav"
  - name: "left_battery_low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/left_battery_low_power.wav"
  - name: "mute"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/mute.wav"
  - name: "over_speed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/over_speed.wav"
  - name: "pms_check_failed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/pms_check_failed.wav"
  - name: "pms_check_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/pms_check_succeed.wav"
  - name: "pms_selftest_timeout"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/pms_selftest_timeout.wav"
  - name: "pose_status_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/pose_status_error.wav"
  - name: "right_battery_low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/right_battery_low_power.wav"
  - name: "shutdown"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/shutdown.wav"
  - name: "stand_up"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/stand_up.wav"
  - name: "turn_off_v48"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/turn_off_v48.wav"
  - name: "left_battery_offline"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery/left_battery_offline.wav"
  - name: "left_battery_online"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery/left_battery_online.wav"
  - name: "right_battery_offline"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery/right_battery_offline.wav"
  - name: "right_battery_online"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery/right_battery_online.wav"
  - name: "low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/battery/low_power.wav"
  - name: "motor_1_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_1_error.wav"
  - name: "motor_2_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_2_error.wav"
  - name: "motor_3_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_3_error.wav"
  - name: "motor_4_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_4_error.wav"
  - name: "motor_5_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_5_error.wav"
  - name: "motor_6_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_6_error.wav"
  - name: "motor_7_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_7_error.wav"
  - name: "motor_8_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/motors_error/motor_8_error.wav"
  - name: "audio_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/audio_error.wav"
  - name: "camera_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/camera_error.wav"
  - name: "camera_normal"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/camera_normal.wav"
  - name: "infrared_tof_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/infrared_tof_error.wav"
  - name: "infrared_tof_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/infrared_tof_succeed.wav"
  - name: "interaction_port_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/interaction_port_error.wav"
  - name: "interaction_port_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/interaction_port_succeed.wav"
  - name: "pose_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/pose_error.wav"
  - name: "pose_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/pose_succeed.wav"
  - name: "quadruped_mode_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/quadruped_mode_error.wav"
  - name: "quadruped_mode_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/quadruped_mode_succeed.wav"
  - name: "temperature_humidity_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/temperature_humidity_error.wav"
  - name: "temperature_humidity_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/temperature_humidity_succeed.wav"
  - name: "ultrasonic_wave_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/ultrasonic_wave_error.wav"
  - name: "ultrasonic_wave_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/ultrasonic_wave_succeed.wav"
  - name: "wifi_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/wifi_error.wav"
  - name: "wifi_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/Chinese/sensors/wifi_succeed.wav"