audio_files:
  - name: "battery_check_failed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/battery_check_failed.wav"
  - name: "boot_up"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/boot_up.wav"
  - name: "controller_connected"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/controller_connected.wav"
  - name: "controller_disconnected"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/controller_disconnected.wav"
  - name: "enter_low_power_mode"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/enter_low_power_mode.wav"
  - name: "exit_low_power_mode"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/exit_low_power_mode.wav"
  - name: "imu_connected"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/imu_connected.wav"
  - name: "imu_disconnected"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/imu_disconnected.wav"
  - name: "left_battery_low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/left_battery_low_power.wav"
  - name: "mute"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/mute.wav"
  - name: "over_speed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/over_speed.wav"
  - name: "pms_check_failed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pms_check_failed.wav"
  - name: "pms_check_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pms_check_succeed.wav"
  - name: "pms_selftest_timeout"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pms_selftest_timeout.wav"
  - name: "pose_status_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pose_status_error.wav"
  - name: "pose_succed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pose_succed.wav"
  - name: "right_battery_low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/right_battery_low_power.wav"
  - name: "shutdown"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/shutdown.wav"
  - name: "stand_up"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/stand_up.wav"
  - name: "turn_off_v48"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/turn_off_v48.wav"
  - name: "left_battery_offline"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/left_battery_offline.wav"
  - name: "left_battery_online"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/left_battery_online.wav"
  - name: "right_battery_offline"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/right_battery_offline.wav"
  - name: "right_battery_online"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/right_battery_online.wav"
  - name: "low_power"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/low_power.wav"
  - name: "motor_1_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_1_error.wav"
  - name: "motor_2_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_2_error.wav"
  - name: "motor_3_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_3_error.wav"
  - name: "motor_4_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_4_error.wav"
  - name: "motor_5_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_5_error.wav"
  - name: "motor_6_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_6_error.wav"
  - name: "motor_7_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_7_error.wav"
  - name: "motor_8_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/motor_8_error.wav"
  - name: "camera_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/camera_error.wav"
  - name: "camera_normal"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/camera_normal.wav"
  - name: "infrared_tof_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/infrared_tof_error.wav"
  - name: "infrared_tof_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/infrared_tof_succeed.wav"
  - name: "pose_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pose_error.wav"
  - name: "pose_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/pose_succeed.wav"
  - name: "temperature_humidity_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/temperature_humidity_error.wav"
  - name: "temperature_humidity_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/temperature_humidity_succeed.wav"
  - name: "ultrasonic_wave_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/ultrasonic_wave_error.wav"
  - name: "ultrasonic_wave_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/ultrasonic_wave_succeed.wav"
  - name: "wifi_error"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/wifi_error.wav"
  - name: "wifi_succeed"
    path: "/home/ziminrsp/code_ws/music-source/44100/English/wifi_succeed.wav"